spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #避免将驼峰命名转换为下划线命名
    database: mysql
    show-sql: true
  mail:
    host: smtp.163.com
    username: mockingjay_xin@163.com
    password: MOCKINGJAY079215
    default-encoding: UTF-8
    protocol: smtp
    port: 25
    properties:
      mail:
        smtp:
          timeout: 25000
          auth: true
          starttls:
            enable: true
            required: true
ip:
  limit:
    minutes: 3
    maxTimes: 6
